### ISSUE TITLE
Can't get it working with aurelia cli project

### ISSUE THREAD

**Issue by clmorales** [michaelmalonenz/aurelia-dragula#31]
Hi, This is a nice aurelia plugin. I installed and works fine but a tried to make a new Aurelia CLI project and I can not get it working. An Aurelia CLI Project Sample will be greate.

**Comment by clmorales** [comment]
Problem solved.  I was missing the dragula.css resource in aurelia.json. Here how to include it.
          {
            "name": "aurelia-dragula",
            "path": "../node_modules/aurelia-dragula/dist/amd",
            "main": "index",
            "resources": [
              "dragula.css"
            ]
          },

**Comment by jadrake75** [comment]
There is still an issue here if you pack for deployment.

The dragula-and-drop.js file is only referenced as a globalResource.  Thus requireJS does not pick it up on trace so it is not included in bundles.  When you pack your bundles and deploy it will not find this file at runtime and fail.

while you can explicitly include it into your packaging scripts it is still "outside" of the bundling.

I do not think this issue is "really" resolved.  Yes you can bundle for development, but you can't pack it for production.

**Comment by avrahamcool** [comment]
this issue should be reopend.

**Comment by michaelmalonenz** [comment]
I would gladly accept pull-requests - I don't know much about the CLI.  I've only used Aurelia + SystemJS

**Comment by avrahamcool** [comment]
no PR needed. we can bundle the plugin with this configuration and everything works great.

```
{
   "name": "aurelia-dragula",
   "path": "../node_modules/aurelia-dragula/dist/amd",
   "main": "index",
   "resources": [
      "dragula-and-drop.js",
      "dragula.css"
   ]
}
```

**Comment by casz** [comment]
@avrahamcool I can't get it to work :(

Am I missing something?

main.ts
```
import {Aurelia} from 'aurelia-framework'
import environment from './environment';

export function configure(aurelia: Aurelia) {
  aurelia.use
    .standardConfiguration()
    .plugin('aurelia-dragula')
```
aurelia.json
```
{
   "name": "aurelia-dragula",
   "path": "../node_modules/aurelia-dragula/dist/amd",
   "main": "index",
   "resources": [
      "dragula-and-drop.js",
      "dragula.css"
   ]
}
```

```
Uncaught TypeError: plugin.load is not a function
    at Module.<anonymous> (vendor-bundle.js:4879)
    at vendor-bundle.js:3918
    at on (vendor-bundle.js:4301)
    at Module.callPlugin (vendor-bundle.js:4739)
    at Module.fetch (vendor-bundle.js:4608)
    at Module.check (vendor-bundle.js:4640)
    at Module.enable (vendor-bundle.js:4960)
    at Module.<anonymous> (vendor-bundle.js:4783)
    at vendor-bundle.js:3918
    at vendor-bundle.js:4973
    at each (vendor-bundle.js:3843)
    at Module.emit (vendor-bundle.js:4972)
    at Module.check (vendor-bundle.js:4722)
    at Module.enable (vendor-bundle.js:4960)
    at Object.enable (vendor-bundle.js:5341)
    at Module.callPlugin (vendor-bundle.js:4882)
```

```
Unhandled rejection Error: Load timeout for modules: template-registry-entry!aurelia-dragula/dragula-and-drop.html_unnormalized2,template-registry-entry!aurelia-dragula/dragula-and-drop.html,text!aurelia-dragula/dragula-and-drop.html_unnormalized3,text!aurelia-dragula/dragula-and-drop.html
http://requirejs.org/docs/errors.html#timeout
    at makeError (http://localhost:9000/scripts/vendor-bundle.js:3952:17)
    at checkLoaded (http://localhost:9000/scripts/vendor-bundle.js:4482:23)
    at http://localhost:9000/scripts/vendor-bundle.js:4503:25
From previous event:
    at DefaultLoader._import (http://localhost:9000/scripts/vendor-bundle.js:13751:14)
    at DefaultLoader.loadTemplate (http://localhost:9000/scripts/vendor-bundle.js:13718:19)
    at ensureRegistryEntry (http://localhost:9000/scripts/vendor-bundle.js:21714:19)
    at ViewEngine.loadViewFactory (http://localhost:9000/scripts/vendor-bundle.js:21782:14)
    at RelativeViewStrategy.loadViewFactory (http://localhost:9000/scripts/vendor-bundle.js:19155:25)
    at HtmlBehaviorResource.load (http://localhost:9000/scripts/vendor-bundle.js:22555:29)
    at ResourceDescription.load (http://localhost:9000/scripts/vendor-bundle.js:21601:28)
    at ResourceModule.load (http://localhost:9000/scripts/vendor-bundle.js:21543:25)
    at http://localhost:9000/scripts/vendor-bundle.js:21911:43
From previous event:
    at ViewEngine.importViewResources (http://localhost:9000/scripts/vendor-bundle.js:21880:52)
    at http://localhost:9000/scripts/vendor-bundle.js:12837:25
From previous event:
    at loadResources (http://localhost:9000/scripts/vendor-bundle.js:12828:9)
    at http://localhost:9000/scripts/vendor-bundle.js:12905:16
    at next (http://localhost:9000/scripts/vendor-bundle.js:12785:32)
    at runTasks (http://localhost:9000/scripts/vendor-bundle.js:12791:12)
    at http://localhost:9000/scripts/vendor-bundle.js:13071:18
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:13070:23
From previous event:
    at FrameworkConfiguration.apply (http://localhost:9000/scripts/vendor-bundle.js:13055:44)
    at Aurelia.start (http://localhost:9000/scripts/vendor-bundle.js:12671:39)
    at Object.configure (http://localhost:9000/scripts/app-bundle.js:57:17)
    at http://localhost:9000/scripts/vendor-bundle.js:11572:29
From previous event:
    at config (http://localhost:9000/scripts/vendor-bundle.js:11567:56)
    at http://localhost:9000/scripts/vendor-bundle.js:11603:14
From previous event:
    at bootstrap (http://localhost:9000/scripts/vendor-bundle.js:11602:26)
    at http://localhost:9000/scripts/vendor-bundle.js:11589:9
    at <anonymous>
From previous event:
    at run (http://localhost:9000/scripts/vendor-bundle.js:11584:61)
    at Object.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:11609:37)
    at Object.execCb (http://localhost:9000/scripts/vendor-bundle.js:5480:33)
    at Module.check (http://localhost:9000/scripts/vendor-bundle.js:4667:51)
    at Module.enable (http://localhost:9000/scripts/vendor-bundle.js:4960:22)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:5341:39)
    at Module.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:4945:33)
    at http://localhost:9000/scripts/vendor-bundle.js:3918:23
    at each (http://localhost:9000/scripts/vendor-bundle.js:3843:31)
    at Module.enable (http://localhost:9000/scripts/vendor-bundle.js:4897:17)
    at Module.init (http://localhost:9000/scripts/vendor-bundle.js:4572:26)
    at http://localhost:9000/scripts/vendor-bundle.js:5244:36
```

**Comment by michaelmalonenz** [comment]
The plugin has since grown an explicit view, so I think (I'm not au fait
with the cli) you will also need to include the 'dragula-and-drop.html' as
a resource.

**Comment by casz** [comment]
Thanks, that was the missing point 👍
